const dealFilters = {
  "Toyota": [
    {
      vehicle: "2026 Toyota Camry",
      trim_package: "LE",
      img: "https://www.buyatoyota.com/sharpr/vcr/adobe/assets/urn:aaid:aem:16726f27-0022-4fc4-9c62-b540a2c97285/as/image.png?",
      down_payment: "$0",
      payment: "$389",
      months: "36",
      disclosure: "Terms available on approved credit through Toyota Financial Services (TFS). Not all customers qualify.",
    },
    {
      vehicle: "2026 Toyota Camry",
      trim_package: "SE",
      img: "https://cdn.sanity.io/images/90qxor39/production/be133fee02dbda1a6f06cb63839385994330aa63-882x344.png?w=882&h=344&q=75&fit=max&auto=format",
      down_payment: "$0",
      payment: "$433",
      months: "36",
      disclosure: "Terms available on approved credit through Toyota Financial Services (TFS). Not all customers qualify.",
    },
    {
      vehicle: "2026 Toyota Corolla",
      trim_package: "LE",
      img: "https://tmna.aemassets.toyota.com/is/image/toyota/toyota/jellies/max/2026/corolla/le/1852/1k3/1.png?fmt=png-alpha&wid=930&hei=328&qlt=90",
      down_payment: "$0",
      payment: "$335",
      months: "36",
      disclosure: "Terms available on approved credit through Toyota Financial Services (TFS). Not all customers qualify.",
    },
    {
      vehicle: "2026 Toyota Corolla",
      trim_package: "SE",
      img: "https://www.buyatoyota.com/sharpr/bat/assets/img/vehicle-info/Corolla/2026/hero-image.png",
      down_payment: "$0",
      payment: "$369",
      months: "36",
      disclosure: "Terms available on approved credit through Toyota Financial Services (TFS). Not all customers qualify.",
    },
    {
      vehicle: "2026 Toyota Corolla",
      trim_package: "LE Hybrid",
      img: "https://www.buyatoyota.com/sharpr/bat/assets/img/vehicle-info/Corolla_Hybrid/2026/hero-image.png",
      down_payment: "$0",
      payment: "$379",
      months: "36",
      disclosure: "Terms available on approved credit through Toyota Financial Services (TFS). Not all customers qualify.",
    },
    {
      vehicle: "2026 Toyota Prius",
      trim_package: "LE",
      img: "https://www.buyatoyota.com/sharpr/bat/assets/img/vehicle-info/Prius/2026/hero-image.png",
      down_payment: "$0",
      payment: "$469",
      months: "36",
      disclosure: "Terms available on approved credit through Toyota Financial Services (TFS). Not all customers qualify.",
    },
    {
      vehicle: "2026 Toyota Prius",
      trim_package: "XLE",
      img: "https://tmna.aemassets.toyota.com/is/image/toyota/toyota/jellies/max/2026/priuspluginhybrid/xse/1237/1m2/36/5.png?fmt=png-alpha&wid=930&hei=328&qlt=90",
      down_payment: "$0",
      payment: "$529",
      months: "36",
      disclosure: "Terms available on approved credit through Toyota Financial Services (TFS). Not all customers qualify.",
    },
    {
      vehicle: "2026 Toyota RAV4",
      trim_package: "LE",
      img: "https://tmna.aemassets.toyota.com/is/image/toyota/toyota/jellies/max/2026/rav4/le/4521/4v8/1.png?fmt=png-alpha&wid=930&hei=328&qlt=90",
      down_payment: "$0",
      payment: "$529",
      months: "36",
      disclosure: "Terms available on approved credit through Toyota Financial Services (TFS). Not all customers qualify.",
    },
    {
      vehicle: "2026 Toyota RAV4",
      trim_package: "XLE",
      img: "https://www.buyatoyota.com/sharpr/bat/assets/img/vehicle-info/RAV4/2026/hero-image.png",
      down_payment: "$0",
      payment: "$575",
      months: "36",
      disclosure: "Terms available on approved credit through Toyota Financial Services (TFS). Not all customers qualify.",
    },
    {
      vehicle: "2026 Toyota RAV4",
      trim_package: "XSE",
      img: "https://delivery.via.assetscs.toyota.com/adobe/assets/urn:aaid:aem:2a7d4cae-5004-4959-83cf-1a89a0189fdb/as/image.png?fmt=png-alpha,rgb,none",
      down_payment: "$0",
      payment: "$629",
      months: "36",
      disclosure: "Terms available on approved credit through Toyota Financial Services (TFS). Not all customers qualify.",
    },
  ],
  "Hyundai": [
    {
      vehicle: "2026 Hyundai Elantra",
      trim_package: "Ecotronic Gray",
      img: "https://media.chromedata.com/MediaGallery/media/MjkzOTU4Xk1lZGlhIEdhbGxlcnk/b8h7e3tpduNOqYbcmWSa6OJqiQxt2kmuUtUwiPVcOI7cPNGbjuDq55i-baDpUWzYr4wJgYZwkqfulEtY-HxLYp9JUAHlW22Ld75zJAPHFzwNgKVKKeP2Wayu1yg6AKowQvVmuaHymNtiV9M7_yw_ZZ90XIIOWqMognK3XdUnSaKvt6WZLXQQGQ/cc_2026HYC021981268_01_640_PE2.png",
      down_payment: "$2,000",
      payment: "$221 + TAX",
      months: "36",
      disclosure: "Terms available on approved credit through Hyundai Financial Services. Not all customers qualify.",
    },
    {
      vehicle: "2026 Hyundai Tucson",
      trim_package: "Hampton Gray",
      img: "https://vehicle-images.carscommerce.inc/stock-images/chrome/053afa15c4d536cb97117bac085ff062.webp",
      down_payment: "$2,000",
      payment: "$263 + TAX",
      months: "36",
      disclosure: "Terms available on approved credit through Hyundai Financial Services. Not all customers qualify.",
    },
    {
      vehicle: "2026 Hyundai Sonata",
      trim_package: "Portofino Gray",
      img: "https://vehicle-images.carscommerce.inc/stock-images/chrome/a9be313c70fdfa60835796c8e4f586bf.png",
      down_payment: "$2,000",
      payment: "$284 + TAX",
      months: "36",
      disclosure: "Terms available on approved credit through Hyundai Financial Services. Not all customers qualify.",
    },
    {
      vehicle: "2026 Hyundai Kona",
      trim_package: "Ecotronic Gray",
      img: "https://s7d1.scene7.com/is/image/hyundai/2026-kona-ice-se-fwd-ecotronic-gray-pearl-centered-browse-hero:Browse?fmt=webp-alpha",
      down_payment: "$2,000",
      payment: "$304 + TAX",
      months: "24",
      disclosure: "Terms available on approved credit through Hyundai Financial Services. Not all customers qualify.",
    },
    {
      vehicle: "2026 Hyundai Santa Fe",
      trim_package: "Shimmering Silver",
      img: "https://media.chromedata.com/MediaGallery/media/MjkzOTU4Xk1lZGlhIEdhbGxlcnk/b8h7e3tpduMylO8nuA_aiwxlSUcg0zyai7yqf7d_k8Uvgrh2wGZtcikUv2A2Pjzw1L1eXEr8bxpv9wJ-Fx_gM7eA9So5kZoyoG9c88qWijpBUu-FO3i-2omDrPKYB70huQUojY6RRp2y1D_YJ-QyBsTMXU7DW-0P1QZoDH0T_4mBtxRzQkZeRw/cc_2026HYS071960644_01_640_R2T.png",
      down_payment: "$2,000",
      payment: "$385 + TAX",
      months: "36",
      disclosure: "Terms available on approved credit through Hyundai Financial Services. Not all customers qualify.",
    },
    {
      vehicle: "2026 Hyundai Palisade",
      trim_package: "Classy Blue Pearl",
      img: "https://vehicle-images.carscommerce.inc/stock-images/chrome/578221fdb42ffc8277d9975931dffd99.png",
      down_payment: "$2,000",
      payment: "$443 + TAX",
      months: "36",
      disclosure: "Terms available on approved credit through Hyundai Financial Services. Not all customers qualify.",
    },
    {
      vehicle: "2026 Hyundai Palisade Hybrid",
      trim_package: "Creamy White Pearl",
      img: "https://vehicle-images.carscommerce.inc/stock-images/chrome/6e7797bd2b135d4382d1489d8349d9e5.png",
      down_payment: "$2,000",
      payment: "$518 + TAX",
      months: "36",
      disclosure: "Terms available on approved credit through Hyundai Financial Services. Not all customers qualify.",
    },
    {
      vehicle: "2026 Hyundai IONIQ 9",
      trim_package: "Base, Snow White Pearl",
      img: "https://alcf.s3.us-west-1.amazonaws.com/_custom/2026/hyundai/ioniq-9/cc_2026hys261969128_01_1280_swp.png",
      down_payment: "$2,000",
      payment: "$488 + TAX",
      months: "36",
      disclosure: "Terms available on approved credit through Hyundai Financial Services. Not all customers qualify.",
    },
  ],
  "Acura": [
    {
      vehicle: "2026 Acura Integra",
      trim_package: "Base",
      img: "https://vehicle-images.carscommerce.inc/stock-images/chrome/1ecfa3cc4b442f7387c14f9a69492ef1.png",
      down_payment: "$2,000",
      payment: "$377",
      months: "36",
      disclosure: "Terms available on approved credit through Acura Financial Services. First time buyers need to present 3 month of statements upfront. MSRP $34,695",
    },
    {
      vehicle: "2026 Acura Integra",
      trim_package: "A Spec",
      img: "https://platform.cstatic-images.com/in/v2/stock_photos/20bd770f-d8d1-4044-b780-2ef779512b98/3d4e1fc5-b485-42b8-b4a0-e1648e973c87.png",
      down_payment: "$2,000",
      payment: "$425",
      months: "36",
      disclosure: "Terms available on approved credit through Acura Financial Services. First time buyers need to present 3 month of statements upfront. MSRP $37,245",
    },
    {
      vehicle: "2026 Acura Integra",
      trim_package: "A Spec Tech",
      img: "https://media.chromedata.com/MediaGallery/media/MjkzOTU4Xk1lZGlhIEdhbGxlcnk/Opm-o5Il9qx9SSefMIYVWd7z7o-Fi00qH1IFAHnOwGl_iOEnFUSG9sL2VsOF6b0dX0ueTAFTSjoEv8ucP79nuhdIxAGPVxddSCOiOUFXPn3o_aIxmaLmG4TEF7PtHSyNu-8LntjIYS6kpoARQ5zsAtsYDHtLSsiCVIy7896TtySVIGRLorIK5w4_ZaalL1J6Tl03ujFooqY/cc_2026ACC012025949_01_640_RE.png",
      down_payment: "$2,000",
      payment: "$496",
      months: "36",
      disclosure: "Terms available on approved credit through Acura Financial Services. First time buyers need to present 3 month of statements upfront. MSRP $41,095",
    },
    {
      vehicle: "2026 Acura ADX",
      trim_package: "Base",
      img: "https://acura.com/-/media/Acura-Platform/Vehicles/2026/adx/AW/Carshot/carshot_ADX_front_ADX_2026_PlatinumWhitePearl_SA1H3TJNW_NH-883P.png",
      down_payment: "$2,000",
      payment: "$427",
      months: "36",
      disclosure: "Terms available on approved credit through Acura Financial Services. First time buyers need to present 3 month of statements upfront. MSRP $37,050",
    },
    {
      vehicle: "2026 Acura ADX",
      trim_package: "A Spec",
      img: "https://vehicle-images.carscommerce.inc/stock-images/thumbnails/large/chrome/ef1daf899f2f152ac2f3c84f875601dc.png",
      down_payment: "$2,000",
      payment: "$469",
      months: "36",
      disclosure: "Terms available on approved credit through Acura Financial Services. First time buyers need to present 3 month of statements upfront. MSRP $39,650",
    },
  ],
  "BMW": [
    {
      vehicle: "2026 BMW 2 Series",
      trim_package: "",
      img: "https://d2ivfcfbdvj3sm.cloudfront.net/wJvHczb1uN2OnS2K/57421/color_no_cr/color_0640_032_png/MY2026/57421/57421_cc0640_032_300.webp?c=172&p=243&m=1&o=png&s=wn916v8q6DPhvCSV46v79P",
      down_payment: "$3,000",
      payment: "$489",
      months: "39",
      disclosure: "Requires BMW Loyalty, 7,500 Miles/Year, 39 month lease. Only aavilable on approved credit through BMW Financial Servies",
    },
    {
      vehicle: "2026 BMW 3 Series",
      trim_package: "",
      img: "https://media.chromedata.com/MediaGallery/media/MjkzOTU4Xk1lZGlhIEdhbGxlcnk/o10qiMPxXkq_NervCG1GUhpoFMp9GTUnOhBRpTVhZ5I1cBa53hBKg96wuk2s5ekxuV7hjZ4hMrJ8BpZmoPA8QNy-eZ8pYyuZL6HzRdVdB52CJIRvFhmMkiB4-nX6YDyYJHqNOG3dy6MlgY3YzObA26lgXI6w6RmQIgNuUZQ9-C5amMJ-IOYCJQ/cc_2026BMC222011554_01_640_300.png",
      down_payment: "$3,000",
      payment: "$489",
      months: "39",
      disclosure: "Requires BMW Loyalty, 7,500 Miles/Year, 39 month lease. Only aavilable on approved credit through BMW Financial Servies",
    },
    {
      vehicle: "2026 BMW 5 Series",
      trim_package: "",
      img: "https://file.kelleybluebookimages.com/kbb/base/evox/CP/57262/2026-BMW-5%20Series-front_57262_032_2400x1800_C64.png",
      down_payment: "$3,000",
      payment: "$689",
      months: "39",
      disclosure: "Requires BMW Loyalty, 7,500 Miles/Year, 39 month lease. Only aavilable on approved credit through BMW Financial Servies",
    },
    {
      vehicle: "2026 BMW X1 Series",
      trim_package: "",
      img: "https://media.chromedata.com/MediaGallery/media/MjkzOTU4Xk1lZGlhIEdhbGxlcnk/o10qiMPxXkqV_WRjKAYUpvIDGvSaI8u6D-TrWMLPVNtFbfcGPL0jIFqHhvHnHl2mOdQOcDz6Yn2-3MpKLW3lvVsYDMPm1pJhatlZO_X_fZoYzMyupCskhhfqEG7SsZinj_jgmtdImqmhiiD64QM9BTDkyOZcpk_cxhsHtxf1IGi3M7vGEYbiJvNzau_7Hmtd1UVII68rEgn_61HKZW1eLA/cc_2026BMS251992528_01_640_C68.png",
      down_payment: "$3,000",
      payment: "$509",
      months: "39",
      disclosure: "Requires BMW Loyalty, 7,500 Miles/Year, 39 month lease. Only aavilable on approved credit through BMW Financial Servies",
    },
  ],
};

export default dealFilters;