const dealFilters = {
  "Toyota": [
    {
      vehicle: "2026 Toyota Camry",
      trim_package: "LE",
      img: "https://www.buyatoyota.com/sharpr/vcr/adobe/assets/urn:aaid:aem:16726f27-0022-4fc4-9c62-b540a2c97285/as/image.png?",
      down_payment: "$0",
      payment: "$389",
      months: "36",
      disclosure: "Terms available on approved credit through Toyota Financial Services (TFS). Not all customers qualify.",
    },
    {
      vehicle: "2026 Toyota Camry",
      trim_package: "SE",
      img: "https://cdn.sanity.io/images/90qxor39/production/be133fee02dbda1a6f06cb63839385994330aa63-882x344.png?w=882&h=344&q=75&fit=max&auto=format",
      down_payment: "$0",
      payment: "$433",
      months: "36",
      disclosure: "Terms available on approved credit through Toyota Financial Services (TFS). Not all customers qualify.",
    },
    {
      vehicle: "2026 Toyota Corolla",
      trim_package: "LE",
      img: "https://tmna.aemassets.toyota.com/is/image/toyota/toyota/jellies/max/2026/corolla/le/1852/1k3/1.png?fmt=png-alpha&wid=930&hei=328&qlt=90",
      down_payment: "$0",
      payment: "$335",
      months: "36",
      disclosure: "Terms available on approved credit through Toyota Financial Services (TFS). Not all customers qualify.",
    },
    {
      vehicle: "2026 Toyota Corolla",
      trim_package: "SE",
      img: "https://www.buyatoyota.com/sharpr/bat/assets/img/vehicle-info/Corolla/2026/hero-image.png",
      down_payment: "$0",
      payment: "$369",
      months: "36",
      disclosure: "Terms available on approved credit through Toyota Financial Services (TFS). Not all customers qualify.",
    },
    {
      vehicle: "2026 Toyota Corolla",
      trim_package: "LE Hybrid",
      img: "https://www.buyatoyota.com/sharpr/bat/assets/img/vehicle-info/Corolla_Hybrid/2026/hero-image.png",
      down_payment: "$0",
      payment: "$379",
      months: "36",
      disclosure: "Terms available on approved credit through Toyota Financial Services (TFS). Not all customers qualify.",
    },
    {
      vehicle: "2026 Toyota Prius",
      trim_package: "LE",
      img: "https://www.buyatoyota.com/sharpr/bat/assets/img/vehicle-info/Prius/2026/hero-image.png",
      down_payment: "$0",
      payment: "$469",
      months: "36",
      disclosure: "Terms available on approved credit through Toyota Financial Services (TFS). Not all customers qualify.",
    },
    {
      vehicle: "2026 Toyota Prius",
      trim_package: "XLE",
      img: "https://tmna.aemassets.toyota.com/is/image/toyota/toyota/jellies/max/2026/priuspluginhybrid/xse/1237/1m2/36/5.png?fmt=png-alpha&wid=930&hei=328&qlt=90",
      down_payment: "$0",
      payment: "$529",
      months: "36",
      disclosure: "Terms available on approved credit through Toyota Financial Services (TFS). Not all customers qualify.",
    },
    {
      vehicle: "2026 Toyota RAV4",
      trim_package: "LE",
      img: "https://tmna.aemassets.toyota.com/is/image/toyota/toyota/jellies/max/2026/rav4/le/4521/4v8/1.png?fmt=png-alpha&wid=930&hei=328&qlt=90",
      down_payment: "$0",
      payment: "$529",
      months: "36",
      disclosure: "Terms available on approved credit through Toyota Financial Services (TFS). Not all customers qualify.",
    },
    {
      vehicle: "2026 Toyota RAV4",
      trim_package: "XLE",
      img: "https://www.buyatoyota.com/sharpr/bat/assets/img/vehicle-info/RAV4/2026/hero-image.png",
      down_payment: "$0",
      payment: "$575",
      months: "36",
      disclosure: "Terms available on approved credit through Toyota Financial Services (TFS). Not all customers qualify.",
    },
    {
      vehicle: "2026 Toyota RAV4",
      trim_package: "XSE",
      img: "https://delivery.via.assetscs.toyota.com/adobe/assets/urn:aaid:aem:2a7d4cae-5004-4959-83cf-1a89a0189fdb/as/image.png?fmt=png-alpha,rgb,none",
      down_payment: "$0",
      payment: "$629",
      months: "36",
      disclosure: "Terms available on approved credit through Toyota Financial Services (TFS). Not all customers qualify.",
    },
  ],
  "Hyundai": [
    {
      vehicle: "2026 Hyundai Elantra",
      trim_package: "Ecotronic Gray",
      img: "https://media.chromedata.com/MediaGallery/media/MjkzOTU4Xk1lZGlhIEdhbGxlcnk/b8h7e3tpduNOqYbcmWSa6OJqiQxt2kmuUtUwiPVcOI7cPNGbjuDq55i-baDpUWzYr4wJgYZwkqfulEtY-HxLYp9JUAHlW22Ld75zJAPHFzwNgKVKKeP2Wayu1yg6AKowQvVmuaHymNtiV9M7_yw_ZZ90XIIOWqMognK3XdUnSaKvt6WZLXQQGQ/cc_2026HYC021981268_01_640_PE2.png",
      down_payment: "$2,000",
      payment: "$221 + TAX",
      months: "36",
      disclosure: "Terms available on approved credit through Hyundai Financial Services. Not all customers qualify.",
    },
    {
      vehicle: "2026 Hyundai Tucson",
      trim_package: "Hampton Gray",
      img: "https://vehicle-images.carscommerce.inc/stock-images/chrome/053afa15c4d536cb97117bac085ff062.webp",
      down_payment: "$2,000",
      payment: "$263 + TAX",
      months: "36",
      disclosure: "Terms available on approved credit through Hyundai Financial Services. Not all customers qualify.",
    },
    {
      vehicle: "2026 Hyundai Sonata",
      trim_package: "Portofino Gray",
      img: "https://vehicle-images.carscommerce.inc/stock-images/chrome/a9be313c70fdfa60835796c8e4f586bf.png",
      down_payment: "$2,000",
      payment: "$284 + TAX",
      months: "36",
      disclosure: "Terms available on approved credit through Hyundai Financial Services. Not all customers qualify.",
    },
    {
      vehicle: "2026 Hyundai Kona",
      trim_package: "Ecotronic Gray",
      img: "https://s7d1.scene7.com/is/image/hyundai/2026-kona-ice-se-fwd-ecotronic-gray-pearl-centered-browse-hero:Browse?fmt=webp-alpha",
      down_payment: "$2,000",
      payment: "$304 + TAX",
      months: "24",
      disclosure: "Terms available on approved credit through Hyundai Financial Services. Not all customers qualify.",
    },
    {
      vehicle: "2026 Hyundai Santa Fe",
      trim_package: "Shimmering Silver",
      img: "https://media.chromedata.com/MediaGallery/media/MjkzOTU4Xk1lZGlhIEdhbGxlcnk/b8h7e3tpduMylO8nuA_aiwxlSUcg0zyai7yqf7d_k8Uvgrh2wGZtcikUv2A2Pjzw1L1eXEr8bxpv9wJ-Fx_gM7eA9So5kZoyoG9c88qWijpBUu-FO3i-2omDrPKYB70huQUojY6RRp2y1D_YJ-QyBsTMXU7DW-0P1QZoDH0T_4mBtxRzQkZeRw/cc_2026HYS071960644_01_640_R2T.png",
      down_payment: "$2,000",
      payment: "$385 + TAX",
      months: "36",
      disclosure: "Terms available on approved credit through Hyundai Financial Services. Not all customers qualify.",
    },
    {
      vehicle: "2026 Hyundai Palisade",
      trim_package: "Classy Blue Pearl",
      img: "https://vehicle-images.carscommerce.inc/stock-images/chrome/578221fdb42ffc8277d9975931dffd99.png",
      down_payment: "$2,000",
      payment: "$443 + TAX",
      months: "36",
      disclosure: "Terms available on approved credit through Hyundai Financial Services. Not all customers qualify.",
    },
    {
      vehicle: "2026 Hyundai Palisade Hybrid",
      trim_package: "Creamy White Pearl",
      img: "https://vehicle-images.carscommerce.inc/stock-images/chrome/6e7797bd2b135d4382d1489d8349d9e5.png",
      down_payment: "$2,000",
      payment: "$518 + TAX",
      months: "36",
      disclosure: "Terms available on approved credit through Hyundai Financial Services. Not all customers qualify.",
    },
    {
      vehicle: "2026 Hyundai IONIQ 9",
      trim_package: "Base, Snow White Pearl",
      img: "https://alcf.s3.us-west-1.amazonaws.com/_custom/2026/hyundai/ioniq-9/cc_2026hys261969128_01_1280_swp.png",
      down_payment: "$2,000",
      payment: "$488 + TAX",
      months: "36",
      disclosure: "Terms available on approved credit through Hyundai Financial Services. Not all customers qualify.",
    },
  ],
};

export default dealFilters;