const dealFilters = {
  Toyota: [
    {
      deal_link: "https://www.buyatoyota.com/socal/offer-detail/?offerid=camry_lease_52f3e6e3-a69c-4a36-b811-bc4a3529e2b9&filters=lease",
      dealer: "Culver City Toyota",
      vehicle: "2026 Camry LE Hybrid",
      trim_package: "",
      img: "https://www.buyatoyota.com/sharpr/vcr/adobe/assets/urn:aaid:aem:80fd067e-3b97-4c19-a582-fb7a40fcbd42/as/image.png?size=680,383&",
      down_payment: "$2,999",
      payment: "$309",
      months: "36",
      disclosure: "Terms available on approved credit through Toyota Financial Services (TFS). Not all customers qualify.",
    },
    {
      deal_link: "dealsByImages/toyota_hollywood.jpg",
      dealer: "Hollywood Toyota",
      vehicle: "2026 Camry LE Hybrid",
      trim_package: "",
      img: "https://www.buyatoyota.com/sharpr/vcr/adobe/assets/urn:aaid:aem:80fd067e-3b97-4c19-a582-fb7a40fcbd42/as/image.png?size=680,383&",
      down_payment: "$3,000",
      payment: "$285",
      months: "39",
      disclosure: "Terms available on approved credit through Toyota Financial Services (TFS). Not all customers qualify.",
    },
    {
      deal_link: "https://www.buyatoyota.com/socal/offer-detail/?offerid=tacoma_lease_4959041b-243e-4abb-ae03-bda3e046a6c1&filters=lease",
      dealer: "Culver City Toyota",
      vehicle: "2026 Tacoma 2WD Double Cab",
      trim_package: "",
      img: "https://www.buyatoyota.com/sharpr/bat/assets/img/vehicles/tacoma/2026/default-offer-detail.png",
      down_payment: "$3,999",
      payment: "$279",
      months: "36",
      disclosure: "Terms available on approved credit through Toyota Financial Services (TFS). Not all customers qualify.",
    },
    {
      deal_link: "https://www.buyatoyota.com/socal/offer-detail/?offerid=corolla_lease_f17b70cf-d3b5-41b8-a121-705c5af05b1d&filters=lease",
      dealer: "Culver City Toyota",
      vehicle: "2026 Corolla 2WD SE",
      trim_package: "",
      img: "https://www.buyatoyota.com/sharpr/vcr/adobe/assets/urn:aaid:aem:0a47e045-79f6-4e46-826c-2465334b5916/as/image.png?size=680,383&",
      down_payment: "$2,999",
      payment: "$259",
      months: "36",
      disclosure: "Terms available on approved credit through Toyota Financial Services (TFS). Not all customers qualify.",
    },
    {
      deal_link: "dealsByImages/toyota_hollywood.jpg",
      dealer: "Hollywood Toyota",
      vehicle: "2026 Toyota Corolla Cross L",
      trim_package: "",
      img: "https://delivery.via.assetscs.toyota.com/adobe/assets/urn:aaid:aem:985425a7-0afc-409a-9bd4-2e3d629d1611/as/image.png?fmt=png-alpha,rgb,none",
      down_payment: "$3,000",
      payment: "$289",
      months: "39",
      disclosure: "Terms available on approved credit through Toyota Financial Services (TFS). Not all customers qualify.",
    },
    {
      deal_link: "https://www.buyatoyota.com/socal/offer-detail/?offerid=corollahybrid_lease_184c073d-9d5d-4300-9844-91f2f8e1341b&filters=lease",
      dealer: "Culver City Toyota",
      vehicle: "2026 Corolla Hybrid LE",
      trim_package: "",
      img: "https://www.buyatoyota.com/sharpr/vcr/adobe/assets/urn:aaid:aem:6e5c074f-a4fa-4658-b670-8912b9732658/as/image.png?size=680,383&",
      down_payment: "$2,999",
      payment: "$269",
      months: "36",
      disclosure: "Terms available on approved credit through Toyota Financial Services (TFS). Not all customers qualify.",
    },
    {
      deal_link: "https://www.buyatoyota.com/socal/offer-detail/?offerid=priuspluginhybrid_lease_7aed34c6-cf7f-4735-b673-791b41d16527&filters=lease",
      dealer: "Culver City Toyota",
      vehicle: "2026 Prius Plug-in Hybrid SE",
      trim_package: "",
      img: "https://www.buyatoyota.com/sharpr/vcr/adobe/assets/urn:aaid:aem:a13719a9-ea99-47d1-b227-98228dcf0100/as/image.png?size=680,383&",
      down_payment: "$2,999",
      payment: "$359",
      months: "36",
      disclosure: "Terms available on approved credit through Toyota Financial Services (TFS). Not all customers qualify.",
    },
    {
      deal_link: "https://www.buyatoyota.com/socal/offer-detail/?offerid=prius_lease_f6a92df4-c6cc-44ba-8540-7e6d8319cfbc&filters=lease",
      dealer: "Culver City Toyota",
      vehicle: "2026 Prius 2WD Sedan LE Hybrid",
      trim_package: "",
      img: "https://www.buyatoyota.com/sharpr/vcr/adobe/assets/urn:aaid:aem:aa04d8a8-35e6-458f-a687-60153284aba1/as/image.png?size=680,383&",
      down_payment: "$2,999",
      payment: "$309",
      months: "36",
      disclosure: "Terms available on approved credit through Toyota Financial Services (TFS). Not all customers qualify.",
    },
  ],
  Hyundai: [
    {
      deal_link: "https://www.hyundaisantamonica.com/best-hyundai-elantra-lease-deals-and-new-specials-in-los-angeles-ca.htm",
      dealer: "Santa Monica Toyota",
      vehicle: "Hyundai Elantra Elantra SE",
      trim_package: "",
      img: "https://api.codifyauto.com/media/files/a6ecbe4e-d47f-412d-9cd5-90f4cd0970e5",
      down_payment: "$3,999",
      payment: "$199 + TAX",
      months: "36",
      disclosure: "On approved credit through Hyundai Motor Finance.",
    },
    {
      deal_link: "https://www.hyundaisantamonica.com/best-hyundai-tucson-lease-deals-and-new-specials-in-los-angeles-ca.htm",
      dealer: "Santa Monica Toyota",
      vehicle: "2026 Hyundai Tucson SE",
      trim_package: "",
      img: "https://api.codifyauto.com/media/dealerships/33b6fdac-ed0f-4352-b9f4-673ceb7d43fd/files/a969cc70-2e4d-4704-9d9c-a8820be1ce59",
      down_payment: "$3,999",
      payment: "$294 + TAX",
      months: "36",
      disclosure: "On approved credit through Hyundai Motor Finance.",
    },
    {
      deal_link: "https://www.hyundaisantamonica.com/best-hyundai-ioniq-5-lease-deals-and-new-specials-in-los-angeles-ca.htm",
      dealer: "Santa Monica Toyota",
      vehicle: "2026 Hyundai IONIQ 5 SE",
      trim_package: "",
      img: "https://api.codifyauto.com/media/files/c6e96866-f07d-4aa5-8058-1d5ac9e8fc69",
      down_payment: "$3,999",
      payment: "$269 + TAX",
      months: "24",
      disclosure: "On approved credit through Hyundai Motor Finance.",
    },
    {
      deal_link: "https://www.hyundaisantamonica.com/best-hyundai-sonata-lease-deals-and-new-specials-in-los-angeles-ca.htm",
      dealer: "Santa Monica Toyota",
      vehicle: "2026 Hyundai Sonata SE",
      trim_package: "",
      img: "https://api.codifyauto.com/media/files/a145448c-47f5-4ecf-8816-24ab753b394c",
      down_payment: "$3,499",
      payment: "$279 + TAX",
      months: "36",
      disclosure: "On approved credit through Hyundai Motor Finance.",
    },
    {
      deal_link: "https://www.hyundaisantamonica.com/best-hyundai-palisade-lease-deals-and-new-specials-in-los-angeles-ca.htm",
      dealer: "Santa Monica Toyota",
      vehicle: "2026 Hyundai Palisade Hybrid SEL",
      trim_package: "",
      img: "https://api.codifyauto.com/media/files/a25b8d7e-3a7f-451d-8c96-ead03de98ce3",
      down_payment: "$3,999",
      payment: "$499 + TAX",
      months: "36",
      disclosure: "On approved credit through Hyundai Motor Finance.",
    },
  ],
  Honda: [
    {
      deal_link: "https://www.culvercityhonda.com/offers-incentives/?view=detail-offer&offerYear=2026&offerMake=Honda&offerModel=Civic%20Sedan&offerTrim=LX&offerBody=4dr%20Car&offerModelCode=11-FE2F2TEW",
      dealer: "Culver City Honda",
      vehicle: "2026 Honda Civic",
      trim_package: "",
      img: "https://media.chromedata.com/MediaGallery/media/MjkzOTU4Xk1lZGlhIEdhbGxlcnk/kgrUOG2zfWlOkHxnoB4HTalJOEqPA6iP_Ylnad4i-bv4P5MLpU3jfT9RmzNfyCVX0MAqvoNDuv9sW9zKfp2bw29_aoQ_Farm-P19En03HxErxfJJf4lmNYbaxcj2Cb-QhG0FLNaaHhr-WcFOFcGOiQ/2026HOC021991696_640_01.png",
      down_payment: "$1,657",
      payment: "$353",
      months: "24",
      disclosure: "Program eligibility based on credit approval. Not all customers will qualify. Offer requires financing with Honda Financial Services.",
    },
    {
      deal_link: "https://www.culvercityhonda.com/offers-incentives/?view=detail-offer&offerYear=2026&offerMake=Honda&offerModel=Accord%20Sedan&offerTrim=LX&offerBody=4dr%20Car&offerModelCode=4-CY1F2TEW",
      dealer: "Culver City Honda",
      vehicle: "2026 Honda Accord",
      trim_package: "",
      img: "https://media.chromedata.com/MediaGallery/media/MjkzOTU4Xk1lZGlhIEdhbGxlcnk/kgrUOG2zfWlDG1EzrvAGx38eMa7y-toBZ_tRtDYK1Qm8MYwuUy45K3CsiLAm0cgOehHNdcZpAeqeW58tx4EDpyncbDz2NvQZ2x7z3YysiQXdGSR_080IXC7wwUT8OnQvBdF5ogiUBbbFSbq5TKosNA/2026HOC012031663_640_01.png",
      down_payment: "$2,071",
      payment: "$447",
      months: "24",
      disclosure: "Program eligibility based on credit approval. Not all customers will qualify. Offer requires financing with Honda Financial Services.",
    },
  ],
  Audi: [
    {
      deal_link: "https://docs.google.com/spreadsheets/d/1RhNM_lPIGGJEgLqAsJBBQW-GZjaaK7swf2vPl_7-dXM/htmlview?utm_source=ig&utm_medium=social&utm_content=link_in_bio&fbclid=PAZnRzaAQ8TFtleHRuA2FlbQIxMQBzcnRjBmFwcF9pZA8xMjQwMjQ1NzQyODc0MTQAAadUZtnRkIv-YWIwVCk_mrMhbDDCdhk9gPHCNkfJxLIjdTBhm1B5u5Jpb_Citw_aem_uzztTKFhXRsFSgR7-UCvsQ",
      dealer: "Audi Santa Monica",
      vehicle: "2026 Audi A3",
      trim_package: "Convenience Black Optics",
      img: "https://cdcssl.ibsrv.net/autodata/images/?img=USD50AUC152A021001.jpg&width=636&height=450",
      down_payment: "$3,000",
      payment: "$363 + TAX",
      months: "39",
      disclosure: "Special eligibility based on credit approval.",
    },
    {
      deal_link: "https://docs.google.com/spreadsheets/d/1RhNM_lPIGGJEgLqAsJBBQW-GZjaaK7swf2vPl_7-dXM/htmlview?utm_source=ig&utm_medium=social&utm_content=link_in_bio&fbclid=PAZnRzaAQ8TFtleHRuA2FlbQIxMQBzcnRjBmFwcF9pZA8xMjQwMjQ1NzQyODc0MTQAAadUZtnRkIv-YWIwVCk_mrMhbDDCdhk9gPHCNkfJxLIjdTBhm1B5u5Jpb_Citw_aem_uzztTKFhXRsFSgR7-UCvsQ",
      dealer: "Audi Santa Monica",
      vehicle: "2026 Audi A6 e-tron",
      trim_package: "Premium Plus, Warm Weather",
      img: "https://mpop-prod-primary.s3.amazonaws.com/audi-chandler-az/img/69b49386a0d00-6e7a3efa-93b7-43a0-ae62-9135f1a53166.jpg",
      down_payment: "$3,000",
      payment: "$795 + TAX",
      months: "36",
      disclosure: "Special eligibility based on credit approval.",
    },
    {
      deal_link: "https://docs.google.com/spreadsheets/d/1RhNM_lPIGGJEgLqAsJBBQW-GZjaaK7swf2vPl_7-dXM/htmlview?utm_source=ig&utm_medium=social&utm_content=link_in_bio&fbclid=PAZnRzaAQ8TFtleHRuA2FlbQIxMQBzcnRjBmFwcF9pZA8xMjQwMjQ1NzQyODc0MTQAAadUZtnRkIv-YWIwVCk_mrMhbDDCdhk9gPHCNkfJxLIjdTBhm1B5u5Jpb_Citw_aem_uzztTKFhXRsFSgR7-UCvsQ",
      dealer: "Audi Santa Monica",
      vehicle: "2026 Audi A6",
      trim_package: "",
      img: "https://www.usnews.com/object/image/0000019c-4ef7-d516-a1dc-4eff34e00000/2026-audi-a6-front-angle-view-left-ak.jpg?update-time=1770851349738&size=responsiveGallery&format=webp",
      down_payment: "$3,000",
      payment: "$766 + TAX",
      months: "36",
      disclosure: "Special eligibility based on credit approval.",
    },
  ],
  Volkswagen: [
    {
      deal_link: "https://www.volkswagenleases.com/quote?vehicle=2026+Jetta+S&img=%2Fassets%2Fimages%2Fspecials%2F2026-jetta-s-1772604767.webp&price=79&term=24&miles=7500&das=4569&tag=Hot+Deal&details=Lease+a+2026+Volkswagen+Jetta+S+for+%2478+%2B+Tax+per+month+for+24+months.+Based+on+an+MSRP+of+%2425%2C566.00+and+a+selling+price+of+%2422%2C871.00.+Stock+%23%3A+NT4212.+%244569+down+includes+drive-off+fees+due+at+signing.+Includes+first+month%E2%80%99s+payment%2C+%24795+acquisition+fee%2C+%2485+documentation+fee%2C+title%2C+license%2C+registration%2C+taxes%2C+and+any+dealer-installed+accessories+or+options.+Lease+includes+7%2C500+miles+per+year+with+an+excess+mileage+charge+of+%240.25+per+mile.+No+security+deposit+required.+Closed-end+lease+%7C+24+months%2C+7%2C500+mi%2Fyr.+%244%2C569+due+at+signing.+All+offers+subject+to+credit+approval+through+Volkswagen+Credit.+Payments+based+on+MSRP+and+may+vary+by+dealer.+Does+not+include+tax%2C+title%2C+license%2C+options%2C+and+dealer+fees.+Lessee+responsible+for+maintenance%2C+excess+wear+and+mileage+over+10%2C000+miles%2Fyear+at+%240.20%2Fmile.+Offers+valid+for+vehicles+in+dealer+stock+only.+Programs+may+change+without+notice.+Offers+valid+in+the+Greater+Los+Angeles+area.+Expires+end+of+month.",
      dealer: "Volkswagen - Puente Hills",
      vehicle: "2026 Jetta S",
      trim_package: "",
      img: "https://www.volkswagenleases.com/assets/images/specials/2026-jetta-s-1772604767.webp",
      down_payment: "$4,569",
      payment: "$79",
      months: "24",
      disclosure: "Special eligibility based on credit approval.",
    },
  ],
};

export default dealFilters;