const dealFilters = {
  "Toyota": [
    {
      vehicle: "2026 Camry LE Hybrid",
      trim_package: "",
      img: "https://www.buyatoyota.com/sharpr/vcr/adobe/assets/urn:aaid:aem:80fd067e-3b97-4c19-a582-fb7a40fcbd42/as/image.png?size=680,383&",
      down_payment: "$2,999",
      payment: "$309",
      months: "36",
      disclosure: "Terms available on approved credit through Toyota Financial Services (TFS). Not all customers qualify.",
    },
    {
      vehicle: "2026 Tacoma 2WD Double Cab",
      trim_package: "",
      img: "https://www.buyatoyota.com/sharpr/bat/assets/img/vehicles/tacoma/2026/default-offer-detail.png",
      down_payment: "$3,999",
      payment: "$279",
      months: "36",
      disclosure: "Terms available on approved credit through Toyota Financial Services (TFS). Not all customers qualify.",
    },
    {
      vehicle: "2026 Camry LE Hybrid",
      trim_package: "",
      img: "https://www.buyatoyota.com/sharpr/vcr/adobe/assets/urn:aaid:aem:80fd067e-3b97-4c19-a582-fb7a40fcbd42/as/image.png?size=680,383&",
      down_payment: "$3,000",
      payment: "$285",
      months: "39",
      disclosure: "Terms available on approved credit through Toyota Financial Services (TFS). Not all customers qualify.",
    },
    {
      vehicle: "2026 Corolla 2WD SE",
      trim_package: "",
      img: "https://www.buyatoyota.com/sharpr/vcr/adobe/assets/urn:aaid:aem:0a47e045-79f6-4e46-826c-2465334b5916/as/image.png?size=680,383&",
      down_payment: "$2,999",
      payment: "$259",
      months: "36",
      disclosure: "Terms available on approved credit through Toyota Financial Services (TFS). Not all customers qualify.",
    },
    {
      vehicle: "2026 Toyota Corolla Cross L",
      trim_package: "",
      img: "https://delivery.via.assetscs.toyota.com/adobe/assets/urn:aaid:aem:985425a7-0afc-409a-9bd4-2e3d629d1611/as/image.png?fmt=png-alpha,rgb,none",
      down_payment: "$3,000",
      payment: "$289",
      months: "39",
      disclosure: "Terms available on approved credit through Toyota Financial Services (TFS). Not all customers qualify.",
    },
    {
      vehicle: "2026 Corolla Hybrid LE",
      trim_package: "",
      img: "https://www.buyatoyota.com/sharpr/vcr/adobe/assets/urn:aaid:aem:6e5c074f-a4fa-4658-b670-8912b9732658/as/image.png?size=680,383&",
      down_payment: "$2,999",
      payment: "$269",
      months: "36",
      disclosure: "Terms available on approved credit through Toyota Financial Services (TFS). Not all customers qualify.",
    },
    {
      vehicle: "2026 Prius Plug-in Hybrid SE",
      trim_package: "",
      img: "https://www.buyatoyota.com/sharpr/vcr/adobe/assets/urn:aaid:aem:a13719a9-ea99-47d1-b227-98228dcf0100/as/image.png?size=680,383&",
      down_payment: "$2,999",
      payment: "$359",
      months: "36",
      disclosure: "Terms available on approved credit through Toyota Financial Services (TFS). Not all customers qualify.",
    },
    {
      vehicle: "2026 Prius 2WD Sedan LE Hybrid",
      trim_package: "",
      img: "https://www.buyatoyota.com/sharpr/vcr/adobe/assets/urn:aaid:aem:aa04d8a8-35e6-458f-a687-60153284aba1/as/image.png?size=680,383&",
      down_payment: "$2,999",
      payment: "$309",
      months: "36",
      disclosure: "Terms available on approved credit through Toyota Financial Services (TFS). Not all customers qualify.",
    },
  ],
  "BMW": [
    {
      vehicle: "2026 2 Series",
      trim_package: "",
      img: "https://d2ivfcfbdvj3sm.cloudfront.net/wJvHczb1uN2OnS2K/57421/color_no_cr/color_0640_032_png/MY2026/57421/57421_cc0640_032_300.webp?c=172&p=243&m=1&o=png&s=wn916v8q6DPhvCSV46v79P",
      down_payment: "$3,000",
      payment: "$489",
      months: "39",
      disclosure: "Requires BMW Loyalty, 7,500 Miles/Year, 39 month lease. Only aavilable on approved credit through BMW Financial Servies",
    },
    {
      vehicle: "2026 3 Series",
      trim_package: "",
      img: "https://gld-creative.s3.us-west-2.amazonaws.com/2026-bmw-3-series-m3-competition-sedan-06b4431b69c3-600x300.png",
      down_payment: "$3,000",
      payment: "$489",
      months: "39",
      disclosure: "Requires BMW Loyalty, 7,500 Miles/Year, 39 month lease. Only aavilable on approved credit through BMW Financial Servies",
    },
    {
      vehicle: "2026 5 Series",
      trim_package: "",
      img: "https://file.kelleybluebookimages.com/kbb/base/evox/CP/57262/2026-BMW-5%20Series-front_57262_032_2400x1800_C64.png",
      down_payment: "$3,000",
      payment: "$689",
      months: "39",
      disclosure: "Requires BMW Loyalty, 7,500 Miles/Year, 39 month lease. Only aavilable on approved credit through BMW Financial Servies",
    },
    {
      vehicle: "2026 X1 Series",
      trim_package: "",
      img: "https://media.chromedata.com/MediaGallery/media/MjkzOTU4Xk1lZGlhIEdhbGxlcnk/o10qiMPxXkqV_WRjKAYUpvIDGvSaI8u6D-TrWMLPVNtFbfcGPL0jIFqHhvHnHl2mOdQOcDz6Yn2-3MpKLW3lvVsYDMPm1pJhatlZO_X_fZoYzMyupCskhhfqEG7SsZinj_jgmtdImqmhiiD64QM9BTDkyOZcpk_cxhsHtxf1IGi3M7vGEYbiJvNzau_7Hmtd1UVII68rEgn_61HKZW1eLA/cc_2026BMS251992528_01_640_C68.png",
      down_payment: "$3,000",
      payment: "$509",
      months: "39",
      disclosure: "Requires BMW Loyalty, 7,500 Miles/Year, 39 month lease. Only aavilable on approved credit through BMW Financial Servies",
    },
  ],
  "Hyundai": [
    {
      vehicle: "Hyundai Elantra Elantra SE",
      trim_package: "",
      img: "https://api.codifyauto.com/media/files/a6ecbe4e-d47f-412d-9cd5-90f4cd0970e5",
      down_payment: "$3,999",
      payment: "$199 + TAX",
      months: "36",
      disclosure: "On approved credit through Hyundai Motor Finance.",
    },
    {
      vehicle: "2026 Hyundai Tucson SE",
      trim_package: "",
      img: "https://api.codifyauto.com/media/dealerships/33b6fdac-ed0f-4352-b9f4-673ceb7d43fd/files/a969cc70-2e4d-4704-9d9c-a8820be1ce59",
      down_payment: "$3,999",
      payment: "$294 + TAX",
      months: "36",
      disclosure: "On approved credit through Hyundai Motor Finance.",
    },
    {
      vehicle: "2026 Hyundai IONIQ 5 SE",
      trim_package: "",
      img: "https://api.codifyauto.com/media/files/c6e96866-f07d-4aa5-8058-1d5ac9e8fc69",
      down_payment: "$3,999",
      payment: "$269 + TAX",
      months: "24",
      disclosure: "On approved credit through Hyundai Motor Finance.",
    },
    {
      vehicle: "2026 Hyundai Sonata SE",
      trim_package: "",
      img: "https://api.codifyauto.com/media/files/a145448c-47f5-4ecf-8816-24ab753b394c",
      down_payment: "$3,499",
      payment: "$279 + TAX",
      months: "36",
      disclosure: "On approved credit through Hyundai Motor Finance.",
    },
    {
      vehicle: "2026 Hyundai Palisade Hybrid SEL",
      trim_package: "",
      img: "https://api.codifyauto.com/media/files/a25b8d7e-3a7f-451d-8c96-ead03de98ce3",
      down_payment: "$3,999",
      payment: "$499 + TAX",
      months: "36",
      disclosure: "On approved credit through Hyundai Motor Finance.",
    },
  ],
  "Honda": [
    {
      vehicle: "2026 Honda Civic",
      trim_package: "",
      img: "https://media.chromedata.com/MediaGallery/media/MjkzOTU4Xk1lZGlhIEdhbGxlcnk/kgrUOG2zfWlOkHxnoB4HTalJOEqPA6iP_Ylnad4i-bv4P5MLpU3jfT9RmzNfyCVX0MAqvoNDuv9sW9zKfp2bw29_aoQ_Farm-P19En03HxErxfJJf4lmNYbaxcj2Cb-QhG0FLNaaHhr-WcFOFcGOiQ/2026HOC021991696_640_01.png",
      down_payment: "$1,657",
      payment: "$353",
      months: "24",
      disclosure: "Program eligibility based on credit approval. Not all customers will qualify. Offer requires financing with Honda Financial Services.",
    },
    {
      vehicle: "2026 Honda Accord",
      trim_package: "",
      img: "https://media.chromedata.com/MediaGallery/media/MjkzOTU4Xk1lZGlhIEdhbGxlcnk/kgrUOG2zfWlDG1EzrvAGx38eMa7y-toBZ_tRtDYK1Qm8MYwuUy45K3CsiLAm0cgOehHNdcZpAeqeW58tx4EDpyncbDz2NvQZ2x7z3YysiQXdGSR_080IXC7wwUT8OnQvBdF5ogiUBbbFSbq5TKosNA/2026HOC012031663_640_01.png",
      down_payment: "$2,071",
      payment: "$447",
      months: "24",
      disclosure: "Program eligibility based on credit approval. Not all customers will qualify. Offer requires financing with Honda Financial Services.",
    },
  ],
  "Audi": [
    {
      vehicle: "2026 Audi A3",
      trim_package: "Convenience Black Optics",
      img: "https://cdcssl.ibsrv.net/autodata/images/?img=USD50AUC152A021001.jpg&width=636&height=450",
      down_payment: "$3,000",
      payment: "$363 + TAX",
      months: "39",
      disclosure: "Special eligibility based on credit approval.",
    },
    {
      vehicle: "2026 Audi A6 e-tron",
      trim_package: "Premium Plus, Warm Weather",
      img: "https://mpop-prod-primary.s3.amazonaws.com/audi-chandler-az/img/69b49386a0d00-6e7a3efa-93b7-43a0-ae62-9135f1a53166.jpg",
      down_payment: "$3,000",
      payment: "$795 + TAX",
      months: "36",
      disclosure: "Special eligibility based on credit approval.",
    },
    {
      vehicle: "2026 Audi A6",
      trim_package: "",
      img: "https://www.usnews.com/object/image/0000019c-4ef7-d516-a1dc-4eff34e00000/2026-audi-a6-front-angle-view-left-ak.jpg?update-time=1770851349738&size=responsiveGallery&format=webp",
      down_payment: "$3,000",
      payment: "$766 + TAX",
      months: "36",
      disclosure: "Special eligibility based on credit approval.",
    },
  ],
  "Volkswagen": [
    {
      vehicle: "2026 Jetta S",
      trim_package: "",
      img: "https://www.volkswagenleases.com/assets/images/specials/2026-jetta-s-1772604767.webp",
      down_payment: "$4,569",
      payment: "$94",
      months: "24",
      disclosure: "Special eligibility based on credit approval.",
    },
    {
      vehicle: "2026 Jetta SE",
      trim_package: "",
      img: "https://www.volkswagenleases.com/assets/images/2026-volkswagen-jetta-s-lease-special.webp",
      down_payment: "$1,500",
      payment: "$264",
      months: "36",
      disclosure: "Special eligibility based on credit approval.",
    },
    {
      vehicle: "2026 Tiguan SE",
      trim_package: "",
      img: "https://www.volkswagenleases.com/assets/images/2026-volkswagen-tiguan-se-lease-special.png",
      down_payment: "$1,104 ",
      payment: "$384",
      months: "36",
      disclosure: "Special eligibility based on credit approval.",
    },
  ],
  "Lexus": [
    {
      vehicle: "2026 Lexus UX 300h",
      trim_package: "",
      img: "https://tmna.assetscs.toyota.com/is/image/lexusaemcs/lexus/images/models/ux/2026/smart-section/lexus-uxh-smart-section-750x471-LEX-UXH-MY23-0014-02.png?wid=750&hei=471&fmt=png-alpha",
      down_payment: "$3,999",
      payment: "$369",
      months: "39",
      disclosure: "Applies to select new 2026 Lexus UX 300h. upon credit approval.",
    },
    {
      vehicle: "2026 Lexus IS 350",
      trim_package: "",
      img: "https://media.rti.toyota.com/adobe/assets/urn:aaid:aem:4b677ee3-9228-47e5-adc5-a7cf3e593eff/as/image.png?size=3256,2936",
      down_payment: "$3,999",
      payment: "$529",
      months: "39",
      disclosure: "Applies to select new 2026 Lexus UX 300h. upon credit approval.",
    },
    {
      vehicle: "2026 Lexus TX 350",
      trim_package: "",
      img: "https://media.rti.toyota.com/adobe/assets/urn:aaid:aem:90bdbd43-bcae-4b24-9502-357c2c340daf/as/image.png?size=3256,2936",
      down_payment: "$4,999",
      payment: "$569",
      months: "39",
      disclosure: "Applies to select new 2026 Lexus UX 300h. upon credit approval.",
    },
  ],
  "Kia": [
    {
      vehicle: "2025 Kia EV6 LIGHT",
      trim_package: "",
      img: "https://vehicle-images.carscommerce.inc/stock-images/chrome/850fea163561a1e570594ad2ffc91fa0.png",
      down_payment: "$2,499",
      payment: "$249",
      months: "24",
      disclosure: "Additional fees apply on the amount due at signing. Requires credit approval and financing through Kia Financial.",
    },
    {
      vehicle: "2025 Kia K4 LXS",
      trim_package: "",
      img: "https://vehicle-images.carscommerce.inc/stock-images/chrome/ac98e4386074ea105794b7ee027242e5.png",
      down_payment: "$1,999",
      payment: "$169",
      months: "24",
      disclosure: "Additional fees apply on the amount due at signing. Requires credit approval and financing through Kia Financial.",
    },
    {
      vehicle: "2026 Kia Sorento LX",
      trim_package: "",
      img: "https://cloudflareimages.dealereprocess.com/resrc/images/c_limit,fl_lossy,w_500/v1/dvp/829/40019849435/New-2026-Kia-Sorento-SWPanoramicSunroof,FWD-ID40019849435-aHR0cDovL2ltYWdlcy51bml0c2ludmVudG9yeS5jb20vdXBsb2Fkcy9waG90b3MvMC8yMDI2LTAzLTAyLzItMjUzNjczMDItNjlhNjRkZWQ5MTJhNC5qcGc=",
      down_payment: "$2,999",
      payment: "$219",
      months: "24",
      disclosure: "Additional fees apply on the amount due at signing. Requires credit approval and financing through Kia Financial.",
    },
    {
      vehicle: "2026 Kia Sportage Hybrid LX",
      trim_package: "",
      img: "https://www.kia.com/content/dam/kia/us/en/vehicles/sportage-hybrid/2026/trims/lx/exterior/adb0b3/360/36.png",
      down_payment: "$2,999",
      payment: "$179",
      months: "24",
      disclosure: "Additional fees apply on the amount due at signing. Requires credit approval and financing through Kia Financial.",
    },
  ],
  "Mazda": [
    {
      vehicle: "2026 Mazda Mazda3 2.5 S Select Sport",
      trim_package: "",
      img: "https://images.jazelc.com/uploads/galpinmazda-m2en/New-2026-Mazda-Mazda3-Sedan-2.5-S-Select-Sport.jpg",
      down_payment: "$1,500",
      payment: "$279 + TAX",
      months: "36",
      disclosure: "On approved credit, not all customers will qualify. The total amount due at signing includes $85 doc fee and first payment.",
    },
    {
      vehicle: "Mazda CX-50 Hybrid",
      trim_package: "Premium",
      img: "https://images.jazelc.com/uploads/galpinmazda-m2en/New-2026-Mazda-CX-50-Hybrid-H-Preferred-2.jpg",
      down_payment: "$1,300",
      payment: "$384 + TAX",
      months: "36",
      disclosure: "On approved credit, not all customers will qualify. The total amount due at signing includes $85 doc fee and first payment.",
    },
  ],
};

export default dealFilters;